### ISSUE TITLE
How to install into eclipse

### ISSUE THREAD

**Issue by mossila** [djaganathan/EclipseToStringBuilderForJson#1]
Sorry for my lack of skill in java and eclipse, I just wanna ask how to add your awesome builder to eclipse. But I stuck here.
<img width="602" alt="screen shot 2560-07-25 at 10 31 24 pm" src="https://user-images.githubusercontent.com/887851/28580236-1f8a429e-7189-11e7-99e4-aa9cb75370c9.png">

**Comment by djaganathan** [comment]
Sorry for the delay. i haven't looked on this for a while.
You have to copy the Class "JsonToStringBuilder.class" into your own project.

![image](https://user-images.githubusercontent.com/26662893/61911210-c2890380-af04-11e9-97fa-614c845999eb.png)

Click OK/OK and your toString method will be nicely as below.

![image](https://user-images.githubusercontent.com/26662893/61911280-0976f900-af05-11e9-9718-3b4ef3e14a10.png)

You can see the output in the log after you print the object.

**Comment by djaganathan** [comment]
i hope the above comment solves your problem
